# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)"'
    restoreKeys: |
       maven | "$(Agent.OS)"
       maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven repository
- task: Maven@3
  displayName: Build project
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'
- task: Maven@3
  displayName: Build docker image
  inputs:
    mavenPomFile: 'dbls-app/pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install -PbuildImage'