spring:
  application:
    name: logger-simulator

configuration:
  data-filepath: data.json
  DEVICE_UUID: 6574444a-5b10-4b0b-9458-682e51736733
  DEVICE_STATUS: OK
  DEVICE_MAC_ADDRESS: 75-10-0B-0E-C8-0E

